//// This file was generated by PermissionsDispatcher. Do not modify!
//package com.example.reconnect.MapPermissions;
//
//import androidx.core.app.ActivityCompat;
//import androidx.fragment.app.Fragment;
//import androidx.legacy.app.FragmentCompat;
//
//import com.example.reconnect.Activities.HomeActivity;
//import com.example.reconnect.fragments.MapFragment;
//
//import permissions.dispatcher.PermissionUtils;
//
//public final class MapDemoActivityPermissionsDispatcher {
//    private static final int REQUEST_GETMYLOCATION = 0;
//
//    private static final String[] PERMISSION_GETMYLOCATIONETMYLOCATION = new String[] {"android.permission.ACCESS_FINE_LOCATION","android.permission.ACCESS_COARSE_LOCATION"};
//
//    private static final int REQUEST_STARTLOCATIONUPDATES = 1;
//
//    private static final String[] PERMISSION_STARTLOCATIONUPDATES = new String[] {"android.permission.ACCESS_FINE_LOCATION","android.permission.ACCESS_COARSE_LOCATION"};
//
//    private MapDemoActivityPermissionsDispatcher() {
//    }
//
//    public static void getMyLocationWithPermissionCheck(MapFragment target) {
//        if (PermissionUtils.hasSelfPermissions(target.getContext(), PERMISSION_GETMYLOCATION)) {
//            target.getMyLocation();
//        } else {
//            Fragment.o(target, PERMISSION_GETMYLOCATION, REQUEST_GETMYLOCATION);
//            ActivityCompat.requestPermissions(target, PERMISSION_GETMYLOCATION, REQUEST_GETMYLOCATION);
//        }
//    }
//
//    public static void startLocationUpdatesWithPermissionCheck(MapFragment target) {
//        if (PermissionUtils.hasSelfPermissions(target.getContext(), PERMISSION_STARTLOCATIONUPDATES)) {
//            target.startLocationUpdates();
//        } else {
//            ActivityCompat.requestPermissions(target, PERMISSION_STARTLOCATIONUPDATES, REQUEST_STARTLOCATIONUPDATES);
//        }
//    }
//
//    public static void onRequestPermissionsResult(MapFragment target, int requestCode,
//                                                  int[] grantResults) {
//        switch (requestCode) {
//            case REQUEST_GETMYLOCATION:
//                if (PermissionUtils.verifyPermissions(grantResults)) {
//                    target.getMyLocation();
//                }
//                break;
//            case REQUEST_STARTLOCATIONUPDATES:
//                if (PermissionUtils.verifyPermissions(grantResults)) {
//                    target.startLocationUpdates();
//                }
//                break;
//            default:
//                break;
//        }
//    }
//}
